### ISSUE TITLE
Channel number for method "start_charge" seems wrong

### ISSUE THREAD

**Issue by Madmaxor** [kroimon/skyrc-ble#1]
In my device Skyrc MC3000 (fw. 1.15 hw >=2.2) channel numbers are: 0,1,3,7 instead of 0,1,2,3

**To Reproduce**
If I use (Python 3.11):
   await mc3000.start_charge(2)
no effect, and:
   await mc3000.start_charge(3)
starts slot 2 on the charger.
If you try different slot numbers you have:
   raise ValueError("Invalid channel")

**Workaround**
My workaround is to change mc3000.py from:

async def start_charge(self, channel: int) -> None:
        """Start charging the battery in the specified channel."""
        if channel not in range(0, MC3000_CHANNEL_COUNT):
            raise ValueError("Invalid channel")

to:

async def start_charge(self, channel: int) -> None:
        """Start charging the battery in the specified channel."""
        if channel not in range(0, MC3000_CHANNEL_COUNT+10):
            raise ValueError("Invalid channel")

and then I have all the 4 channels working, with index 0,1,3,7.

**Comment by Madmaxor** [comment]
A more "clean" solution could be to modify the file skyrc-ble-main/src/skyrc_ble/mc3000.py this way:
```

--- mc3000.py	2023-01-26 15:48:44.000000000 +0100
+++ ../mc3000_fixed.py	2023-10-26 17:27:02.000000000 +0200
@@ -38,6 +38,7 @@
 STRUCT_GET_VERSION_INFO = Struct(">xxxxxxxxxxxxBBB")
 STRUCT_GET_BASIC_DATA = Struct(">B?B?BH")
 
+CHN_NUM=[0,1,3,7]
 
 class Mc3000(SkyRcDevice[Mc3000State]):
 
@@ -77,13 +78,13 @@
         """Start charging the battery in the specified channel."""
         if channel not in range(0, MC3000_CHANNEL_COUNT):
             raise ValueError("Invalid channel")
-        await self._send_packet(CMD_START_CHARGE, [channel + 1])
+       await self._send_packet(CMD_START_CHARGE, [CHN_NUM[channel] + 1])
 
     async def stop_charge(self, channel: int) -> None:
         """Stop charging the battery in the specified channel."""
         if channel not in range(0, MC3000_CHANNEL_COUNT):
             raise ValueError("Invalid channel")
-        await self._send_packet(CMD_STOP_CHARGE, [channel + 1])
+       await self._send_packet(CMD_STOP_CHARGE, [CHN_NUM[channel] + 1])
 
     async def _send_packet(self, command: int, payload: list[int] = []) -> None:
         """Send a packet to the device."""

```

**Comment by kroimon** [comment]
You are right, the channel index for the start and stop commands is a bit field, so the indexes are 1, 2, 4, and 8.
This could be used to start multiple channels at once (e.g. 6 would start channels 2 and 3, or 15 would start all channels).

Thanks for reporting this!
